name: data_pipe
description: >-
  An universal pump for data. It converted any formatted data to another any formatted data.
repository: https://github.com/signmotion/data_pipe
topics:
  - converter
  - data
  - image
  - formatter
  - json

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ">=1.10.0 <3.0.0"
  path: ">=1.8.3 <3.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
